// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ngCodeGen.CodeTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    using System.IO;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class WebAzureYamlCDPipeline : WebAzureYamlCDPipelineBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            
            #line 14 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"

Deployment data = JsonConvert.DeserializeObject<Deployment>(this.deployment);

var stages = data.WebDeploymentStages;
var defaultLocation = data.DefaultLocation;
var poolName = data.PoolName;
var vmImage = string.IsNullOrEmpty(data.VmImage) ? "" : $"vmimage: {data.VmImage}";
var useIndependentPlan = data.UseIndependentPlan;

// DO NOT WIPE THE SOURCE CODE...
var codeGenPath = $"{this.rootTemplatePath}codegen\\";

// TEMPLATE CODE HERE

            
            #line default
            #line hidden
            this.Write("name: $(BuildID)\r\npool: \r\n  name: ");
            
            #line 30 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(poolName));
            
            #line default
            #line hidden
            this.Write("\r\n  ");
            
            #line 31 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(vmImage));
            
            #line default
            #line hidden
            this.Write("\r\ntrigger:\r\n- develop\r\n- releases/*\r\n- master\r\n\r\nstages:\r\n");
            
            #line 38 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"

// provision deployment stages   
for (Int32 i = 0; i < stages.Length; ++i) {
	var stage = stages[i];
    
    var subscriptionId = stage.SubscriptionId;
    var deploymentLocation = stage.DeploymentLocation;
    var deploymentLocationName = stage.DeploymentLocationName;
    var azureServiceConnectionName = stage.AzureServiceConnectionName;
    var resourceGroup = stage.ResourceGroup;
    var teamResourceGroup = stage.TeamResourceGroup;
    var azureTeamServiceConnectionName = stage.AzureTeamServiceConnectionName;
    var environment = stage.Environment;
    var customCondition = "eq(variables['Build.SourceBranch'], '')";
    var buildSourceBranch = stage.BuildSourceBranch;

    if (environment.ToLower() == "int") {
        customCondition = "eq(variables['Build.SourceBranch'], 'refs/heads/develop')";
    
            
            #line default
            #line hidden
            this.Write("  - stage: VALIDATE\r\n    jobs:\r\n    - deployment: Validation\r\n      displayName: " +
                    "Validate Template\r\n      environment: ");
            
            #line 60 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(environment.ToLower()));
            
            #line default
            #line hidden
            this.Write("     \r\n");
            
            #line 61 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
 if (!useIndependentPlan) {
            
            #line default
            #line hidden
            this.Write(@"    - job: VALIDATESERVICEPLAN
      condition: and(succeeded(), and(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Deploy'], 'true')))
      steps:
      - task: AzureResourceGroupDeployment@2
        displayName: 'Validate Template'
        inputs:
          azureSubscription: '");
            
            #line 68 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(azureTeamServiceConnectionName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          resourceGroupName: \'");
            
            #line 69 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(teamResourceGroup));
            
            #line default
            #line hidden
            this.Write("\'\r\n          location: \'");
            
            #line 70 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deploymentLocationName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          csmFile: \'ArmTemplate/azuredeploy.servicePlan.json\'\r\n          csmPa" +
                    "rametersFile: \'ArmTemplate/azuredeploy.servicePlan.parameters.");
            
            #line 72 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stage.Name));
            
            #line default
            #line hidden
            this.Write(".json\'\r\n          deploymentMode: Validation\r\n       \r\n      - task: AzureResourc" +
                    "eGroupDeployment@2\r\n        displayName: \'Validate Template\'\r\n        inputs:\r\n " +
                    "         azureSubscription: \'");
            
            #line 78 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(azureServiceConnectionName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          resourceGroupName: \'");
            
            #line 79 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resourceGroup));
            
            #line default
            #line hidden
            this.Write("\'\r\n          location: \'");
            
            #line 80 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deploymentLocationName));
            
            #line default
            #line hidden
            this.Write(@"'
          csmFile: ArmTemplate/azuredeploy.json
          csmParametersFile: ArmTemplate/azuredeploy.parameters.json
          overrideParameters: '-Environment int -AppServiceSslCertificateName TempPipelineValue -AppServiceCustomHostname TempPipelineValue -AppServiceBlueSlotCustomHostname TempPipelineValue'
          deploymentMode: Validation
");
            
            #line 85 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
} else {
            
            #line default
            #line hidden
            this.Write(@"    - job: VALIDATEAPP
      condition: and(succeeded(), and(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Deploy'], 'true')))
      steps:
      - task: AzureResourceGroupDeployment@2
        displayName: 'Validate Template'
        inputs:
          azureSubscription: '");
            
            #line 92 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(azureServiceConnectionName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          resourceGroupName: \'");
            
            #line 93 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resourceGroup));
            
            #line default
            #line hidden
            this.Write("\'\r\n          location: \'");
            
            #line 94 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deploymentLocationName));
            
            #line default
            #line hidden
            this.Write(@"'
          csmFile: ArmTemplate/azuredeploy.json
          csmParametersFile: ArmTemplate/azuredeploy.parameters.json
          overrideParameters: '-Environment int -AppServiceSslCertificateName TempPipelineValue -AppServiceCustomHostname TempPipelineValue -AppServiceBlueSlotCustomHostname TempPipelineValue'
          deploymentMode: Validation
");
            
            #line 99 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
}
            
            #line default
            #line hidden
            
            #line 99 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"

    }
    else if (environment.ToLower() == "qa" || environment.ToLower() == "test") {
        customCondition = "startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')";
    }
    else if (environment.ToLower() == "can") {
        customCondition = "or(startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))";
    }
    else if (environment.ToLower() == "prod") {
        customCondition = "eq(variables['Build.SourceBranch'], 'refs/heads/master')";
    } else {
        customCondition = $"eq(variables['Build.SourceBranch'], {buildSourceBranch})";
    }
            
            #line default
            #line hidden
            this.Write("  - stage: ");
            
            #line 111 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stage.Name.ToUpper().Replace("-","_").Replace(".","_")));
            
            #line default
            #line hidden
            this.Write("\r\n    condition: ");
            
            #line 112 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customCondition));
            
            #line default
            #line hidden
            this.Write("\r\n    jobs:\r\n    - deployment: ");
            
            #line 114 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(environment));
            
            #line default
            #line hidden
            this.Write("Deployment \r\n      displayName: Deploy Template To ");
            
            #line 115 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(environment.ToLower()));
            
            #line default
            #line hidden
            this.Write(" \r\n      environment: ");
            
            #line 116 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(environment.ToLower()));
            
            #line default
            #line hidden
            this.Write("  \r\n");
            
            #line 117 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
 if (!useIndependentPlan) {
            
            #line default
            #line hidden
            this.Write("    - job: deployServicePlanAndApp");
            
            #line 118 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(environment.ToLower()));
            
            #line default
            #line hidden
            this.Write("\r\n      condition: and(succeeded(), ");
            
            #line 119 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customCondition));
            
            #line default
            #line hidden
            this.Write(")\r\n      steps:\r\n      - task: AzureResourceManagerTemplateDeployment@3\r\n        " +
                    "displayName: \'ARM Template deployment: Resource Group scope\'\r\n        inputs:\r\n " +
                    "         azureResourceManagerConnection: \'");
            
            #line 124 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(azureTeamServiceConnectionName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          subscriptionId: \'");
            
            #line 125 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(subscriptionId));
            
            #line default
            #line hidden
            this.Write("\'\r\n          resourceGroupName: \'");
            
            #line 126 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(teamResourceGroup));
            
            #line default
            #line hidden
            this.Write("\'\r\n          location: \'");
            
            #line 127 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deploymentLocationName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          templateLocation: \'Linked artifact\'\r\n          csmFile: \'ArmTemplate" +
                    "/azuredeploy.servicePlan.json\'\r\n          csmParametersFile: \'ArmTemplate/azured" +
                    "eploy.servicePlan.parameters.");
            
            #line 130 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stage.Name));
            
            #line default
            #line hidden
            this.Write(".json\'\r\n          deploymentMode: Incremental\r\n      \r\n      - task: AzureResourc" +
                    "eManagerTemplateDeployment@3\r\n        displayName: \'ARM Template deployment: Res" +
                    "ource Group scope\'\r\n        inputs:\r\n          azureResourceManagerConnection: \'" +
                    "");
            
            #line 136 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(azureServiceConnectionName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          subscriptionId: \'");
            
            #line 137 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(subscriptionId));
            
            #line default
            #line hidden
            this.Write("\'\r\n          resourceGroupName: \'");
            
            #line 138 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resourceGroup));
            
            #line default
            #line hidden
            this.Write("\'\r\n          location: \'");
            
            #line 139 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deploymentLocationName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          templateLocation: \'Linked artifact\'\r\n          csmFile: \'ArmTemplate" +
                    "/azuredeploy.json\'\r\n          csmParametersFile: \'ArmTemplate/azuredeploy.parame" +
                    "ters.");
            
            #line 142 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stage.Name));
            
            #line default
            #line hidden
            this.Write(".json\'\r\n          deploymentMode: Incremental\r\n");
            
            #line 144 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
} else {
            
            #line default
            #line hidden
            this.Write("    - job: deployServicePlanAndApp");
            
            #line 145 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(environment.ToLower()));
            
            #line default
            #line hidden
            this.Write("\r\n      condition: and(succeeded(), ");
            
            #line 146 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customCondition));
            
            #line default
            #line hidden
            this.Write(")\r\n      steps:\r\n      - task: AzureResourceManagerTemplateDeployment@3\r\n        " +
                    "displayName: \'ARM Template deployment: Resource Group scope\'\r\n        inputs:\r\n " +
                    "         azureResourceManagerConnection: \'");
            
            #line 151 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(azureServiceConnectionName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          subscriptionId: \'");
            
            #line 152 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(subscriptionId));
            
            #line default
            #line hidden
            this.Write("\'\r\n          resourceGroupName: \'");
            
            #line 153 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resourceGroup));
            
            #line default
            #line hidden
            this.Write("\'\r\n          location: \'");
            
            #line 154 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deploymentLocationName));
            
            #line default
            #line hidden
            this.Write("\'\r\n          templateLocation: \'Linked artifact\'\r\n          csmFile: \'ArmTemplate" +
                    "/azuredeploy.json\'\r\n          csmParametersFile: \'ArmTemplate/azuredeploy.parame" +
                    "ters.");
            
            #line 157 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stage.Name));
            
            #line default
            #line hidden
            this.Write(".json\'\r\n          deploymentMode: Incremental");
            
            #line 158 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"
}

            
            #line default
            #line hidden
            
            #line 159 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"

    // END TEMPLATE CODE
}

SaveOutputToSubFolder(codeGenPath, $"{data.Id}\\{data.TeamName.ToLower()}-{data.Name.ToLower()}-infra\\CD", "azure-pipelines.yml");    

            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 166 "C:\research\azure-deploy\CodeTemplates\WebAzureYamlCDPipeline.tt"

private void SaveOutputToSubFolder(string rootTemplatePath, string folderName, string outputFileName) {
  string templateDirectory = Path.GetDirectoryName(rootTemplatePath.Replace('\\', Path.DirectorySeparatorChar));
  string newDirectoryName = Path.Combine(templateDirectory,folderName.Replace('\\', Path.DirectorySeparatorChar));
  if(!Directory.Exists(newDirectoryName))
  {  
	Directory.CreateDirectory(newDirectoryName);
  }
  string outputFilePath = Path.Combine(newDirectoryName, outputFileName.Replace('\\', Path.DirectorySeparatorChar));
  File.WriteAllText(outputFilePath, this.GenerationEnvironment.ToString()); 
  this.GenerationEnvironment.Remove(0, this.GenerationEnvironment.Length);
}

private readonly string deployment;
private readonly string rootTemplatePath;
public WebAzureYamlCDPipeline(string deployment, string rootTemplatePath) {
    this.deployment = deployment;
    this.rootTemplatePath = rootTemplatePath;
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class WebAzureYamlCDPipelineBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
